### ISSUE TITLE
Fluids can be taken from claims

### ISSUE THREAD

**Issue by CrazyPyroEagle** [RysingDragon/LandProtect#1]
When using an empty bucket to pick up fluid sources inside a claim, you get the filled bucket despite not having access to that claim. Due to that, you also get to keep the empty bucket and the source never disappears.

This may be a SpongeForge bug cancelling the corresponding event, but you'll have to check it's not on your side first.

**Comment by DawnTheFawn1** [comment]
I am unable to reproduce this using the latest build of SpongeForge so unless more information can be given I will assume that this is not a bug with LandProtect.
